### ISSUE TITLE
Task 1: Desarrollo Endpoint para registro de usuario - Desarrollo DTOs y Mappers. Desarrollo Controlador: Delete-commit, Insert-commit, etc. TestUnitarios: TestDelete-commit, testInsert-commit, etc.

### ISSUE THREAD

**Issue by jdeleonferreira** [jdeleonferreira/Facurador#27]
## Descripción:
Esta user story está relacionada con #17, que consiste en permitir a los usuarios registrarse en la plataforma. El objetivo de esta tarea es implementar la funcionalidad del registro de usuario, asegurando que los datos se almacenen correctamente en la base de datos y se manejen adecuadamente los casos de error.

## Detalles:
Objetivo: Desarrollar la funcionalidad de registro de usuario.

### Requisitos:
-
-

## Criterios de Aceptación:
-
-

## Consideraciones Técnicas:
- 
-

## Dependencias:
-
-

**Comment by jdeleonferreira** [comment]
Esta tarea está relacionada con la historia de usuario #17

**Comment by Deiverso-JM** [comment]
## **Diagram Task approach**





![Image](https://github.com/jdeleonferreira/Facturador/assets/78669689/4a0a7ea2-2009-4785-a4fe-ad2d21633918)
